// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsLCG7o2B3VO1_Vwl4jGKC__FiAukxIcA',
    appId: '1:163253019109:web:78aa892aadece3b7870f0c',
    messagingSenderId: '163253019109',
    projectId: 'beruang-app-7007e',
    authDomain: 'beruang-app-7007e.firebaseapp.com',
    storageBucket: 'beruang-app-7007e.firebasestorage.app',
    measurementId: 'G-6ET6YKEWFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6MkPJtdhD7RNRKwd-aCVqjyW4mYTvIkU',
    appId: '1:163253019109:android:0704ea4802ecc3d1870f0c',
    messagingSenderId: '163253019109',
    projectId: 'beruang-app-7007e',
    storageBucket: 'beruang-app-7007e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5rJrauiw0ZbKDZswF1S_f3VZWj7elU5A',
    appId: '1:163253019109:ios:8300b8cbe140115a870f0c',
    messagingSenderId: '163253019109',
    projectId: 'beruang-app-7007e',
    storageBucket: 'beruang-app-7007e.firebasestorage.app',
    iosBundleId: 'com.hazellenuts.beruang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5rJrauiw0ZbKDZswF1S_f3VZWj7elU5A',
    appId: '1:163253019109:ios:8300b8cbe140115a870f0c',
    messagingSenderId: '163253019109',
    projectId: 'beruang-app-7007e',
    storageBucket: 'beruang-app-7007e.firebasestorage.app',
    iosBundleId: 'com.hazellenuts.beruang',
  );

}